const fs = require('fs');
const path = require('path');

// Read .env file from project root
const envPath = path.join(__dirname, '..', '.env');
const envContent = fs.readFileSync(envPath, 'utf8');

// Parse VITE_BACKEND_IP from .env
let backendIP = 'localhost';
let backendPort = '5000';

envContent.split('\n').forEach(line => {
  if (line.startsWith('VITE_BACKEND_IP=')) {
    backendIP = line.split('=')[1].trim();
  }
  if (line.startsWith('VITE_BACKEND_PORT=')) {
    backendPort = line.split('=')[1].trim();
  }
});

// Generate Java TestConfig file
const javaConfig = `// ============================================================================
// AUTO-GENERATED FROM ROOT .env FILE - DO NOT EDIT MANUALLY
// ============================================================================
// This file is automatically generated by sync-config.js
// To change backend IP, edit the root .env file and run: node qa-suite/sync-config.js
// ============================================================================

package com.saaya;

public class TestConfig {
    // Auto-loaded from root .env file
    public static final String BACKEND_IP = "${backendIP}";
    public static final String BACKEND_PORT = "${backendPort}";
    
    // Auto-generated URLs (Don't modify)
    public static final String BASE_URL = "http://" + BACKEND_IP + ":" + BACKEND_PORT;
    public static final String HEALTH_URL = BASE_URL + "/api/health";
    public static final String ALERTS_URL = BASE_URL + "/api/alerts";
    public static final String STATS_URL = BASE_URL + "/api/stats";
    public static final String TELEMETRY_URL = BASE_URL + "/api/telemetry";
}
`;

// Write to Java test config
const javaConfigPath = path.join(__dirname, 'src', 'test', 'java', 'com', 'saaya', 'TestConfig.java');
fs.writeFileSync(javaConfigPath, javaConfig);

console.log('✅ TestConfig.java updated with BACKEND_IP:', backendIP);
