// ============================================================================
// AUTO-GENERATED FROM ROOT .env FILE - DO NOT EDIT MANUALLY
// ============================================================================
// This file is automatically generated by sync-config.js
// To change backend IP, edit the root .env file and run: node qa-suite/sync-config.js
// ============================================================================

package com.saaya;

public class TestConfig {
    // Auto-loaded from root .env file
    public static final String BACKEND_IP = "localhost";
    public static final String BACKEND_PORT = "5000";
    
    // Auto-generated URLs (Don't modify)
    public static final String BASE_URL = "http://" + BACKEND_IP + ":" + BACKEND_PORT;
    public static final String HEALTH_URL = BASE_URL + "/api/health";
    public static final String ALERTS_URL = BASE_URL + "/api/alerts";
    public static final String STATS_URL = BASE_URL + "/api/stats";
    public static final String TELEMETRY_URL = BASE_URL + "/api/telemetry";
}
