apiVersion: v1
kind: ConfigMap
metadata:
  name: saaya-config
  namespace: default
data:
  # Change this IP when you get new EC2 instance
  BACKEND_IP: "34.206.71.217"
  VITE_BACKEND_IP: "34.206.71.217"
  VITE_BACKEND_PORT: "5000"
  PORT: "5000"
  HOST: "0.0.0.0"
  NODE_ENV: "production"
