export const mockAlerts = [
  {
    deviceId: "Saaya_001",
    status: "SOS",
    location: "Chandni Chowk, Delhi",
    coordinates: [28.6506, 77.2303],
    timestamp: new Date().toISOString(),
    heartRate: 145,
  },
  {
    deviceId: "Saaya_002",
    status: "Normal",
    location: "Marine Drive, Mumbai",
    coordinates: [18.9440, 72.8238],
    timestamp: new Date().toISOString(),
    heartRate: 75,
  },
  {
    deviceId: "Saaya_003",
    status: "SOS",
    location: "Koramangala, Bangalore",
    coordinates: [12.9352, 77.6245],
    timestamp: new Date().toISOString(),
    heartRate: 160,
  },
  {
    deviceId: "Saaya_004",
    status: "Normal",
    location: "Park Street, Kolkata",
    coordinates: [22.5550, 88.3510],
    timestamp: new Date().toISOString(),
    heartRate: 68,
  },
  {
    deviceId: "Saaya_005",
    status: "Normal",
    location: "Marina Beach, Chennai",
    coordinates: [13.0475, 80.2824],
    timestamp: new Date().toISOString(),
    heartRate: 80,
  },
  {
    deviceId: "Saaya_006",
    status: "SOS",
    location: "Hawa Mahal, Jaipur",
    coordinates: [26.9239, 75.8267],
    timestamp: new Date().toISOString(),
    heartRate: 152,
  },
  {
    deviceId: "Saaya_007",
    status: "Normal",
    location: "Sabarmati Ashram, Ahmedabad",
    coordinates: [23.0597, 72.5807],
    timestamp: new Date().toISOString(),
    heartRate: 70,
  },
  {
    deviceId: "Saaya_008",
    status: "SOS",
    location: "Charminar, Hyderabad",
    coordinates: [17.3616, 78.4747],
    timestamp: new Date().toISOString(),
    heartRate: 158,
  },
  {
    deviceId: "Saaya_009",
    status: "Normal",
    location: "Koregaon Park, Pune",
    coordinates: [18.5362, 73.8940],
    timestamp: new Date().toISOString(),
    heartRate: 74,
  },
  {
    deviceId: "Saaya_010",
    status: "Normal",
    location: "Hazratganj, Lucknow",
    coordinates: [26.8467, 80.9462],
    timestamp: new Date().toISOString(),
    heartRate: 71,
  },
  {
    deviceId: "Saaya_011",
    status: "SOS",
    location: "Fort Kochi, Kerala",
    coordinates: [9.9640, 76.2240],
    timestamp: new Date().toISOString(),
    heartRate: 165,
  },
  {
    deviceId: "Saaya_012",
    status: "Normal",
    location: "Upper Lake, Bhopal",
    coordinates: [23.2450, 77.3820],
    timestamp: new Date().toISOString(),
    heartRate: 69,
  },
  {
    deviceId: "Saaya_013",
    status: "SOS",
    location: "Paltan Bazaar, Guwahati",
    coordinates: [26.1806, 91.7516],
    timestamp: new Date().toISOString(),
    heartRate: 148,
  },
  {
    deviceId: "Saaya_014",
    status: "Normal",
    location: "Sector 17, Chandigarh",
    coordinates: [30.7333, 76.7794],
    timestamp: new Date().toISOString(),
    heartRate: 73,
  },
  {
    deviceId: "Saaya_015",
    status: "SOS",
    location: "Lingaraj Temple, Bhubaneswar",
    coordinates: [20.2393, 85.8335],
    timestamp: new Date().toISOString(),
    heartRate: 155,
  },
];